# BBDM model architecture for IR -> RGB. Must match the checkpoint in
# Hugging Face: skl24/RGBT -> bbdm_ir2rgb/weights/last_model.pth
model:
  model_name: "BrownianBridge"
  model_type: "BBDM"
  latent_before_quant_conv: False
  normalize_latent: False
  only_load_latent_mean_std: False

  EMA:
    use_ema: True
    ema_decay: 0.995
    update_ema_interval: 8
    start_ema_step: 30000

  CondStageParams:
    n_stages: 2
    in_channels: 3
    out_channels: 3

  BB:
    optimizer:
      weight_decay: 0.000
      optimizer: 'Adam'
      lr: 1.e-4
      beta1: 0.9
    lr_scheduler:
      factor: 0.5
      patience: 3000
      threshold: 0.0001
      cooldown: 3000
      min_lr: 5.e-7
    params:
      mt_type: 'linear'
      objective: 'grad'
      loss_type: 'l1'
      skip_sample: True
      sample_type: 'linear'
      sample_step: 200
      num_timesteps: 1000
      eta: 1.0
      max_var: 1.0
      UNetParams:
        image_size: 128
        in_channels: 6
        model_channels: 128
        out_channels: 3
        num_res_blocks: 2
        attention_resolutions: !!python/tuple
          - 64
          - 32
          - 16
        channel_mult: !!python/tuple
          - 1
          - 4
          - 8
        conv_resample: True
        dims: 2
        num_heads: 8
        num_head_channels: 64
        use_scale_shift_norm: True
        resblock_updown: True
        use_spatial_transformer: False
        context_dim:
        condition_key: "SpatialRescaler"
